//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MW_Online.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MW_Online.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pichalka {
            get {
                object obj = ResourceManager.GetObject("pichalka", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string TEXT_CANCEL_BUTTON_EN {
            get {
                return ResourceManager.GetString("TEXT_CANCEL_BUTTON_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string TEXT_CANCEL_BUTTON_RU {
            get {
                return ResourceManager.GetString("TEXT_CANCEL_BUTTON_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download.
        /// </summary>
        internal static string TEXT_DOWNLOAD_BUTTON_EN {
            get {
                return ResourceManager.GetString("TEXT_DOWNLOAD_BUTTON_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скачать.
        /// </summary>
        internal static string TEXT_DOWNLOAD_BUTTON_RU {
            get {
                return ResourceManager.GetString("TEXT_DOWNLOAD_BUTTON_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This version of MW-Online Client is outdated. You won&apos;t be able to play online until the update. Press Update to start the updation process and start the game, pressing Cancel will start the game in singleplayer..
        /// </summary>
        internal static string TEXT_OUTDATED_EN {
            get {
                return ResourceManager.GetString("TEXT_OUTDATED_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия MW-Online устарела. Вы не сможете играть, пока не обновите её. Нажмите кнопку &quot;Обновить&quot;, чтобы начать процесс обновления или нажмите &quot;Отмена&quot;, чтобы перейти в одиночную игру..
        /// </summary>
        internal static string TEXT_OUTDATED_RU {
            get {
                return ResourceManager.GetString("TEXT_OUTDATED_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update.
        /// </summary>
        internal static string TEXT_UPDATE_BUTTON_EN {
            get {
                return ResourceManager.GetString("TEXT_UPDATE_BUTTON_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        internal static string TEXT_UPDATE_BUTTON_RU {
            get {
                return ResourceManager.GetString("TEXT_UPDATE_BUTTON_RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MW-Online: Outdated version.
        /// </summary>
        internal static string TEXT_UPDATEFORM_CAPTION_EN {
            get {
                return ResourceManager.GetString("TEXT_UPDATEFORM_CAPTION_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MW-Online: Версия устарела.
        /// </summary>
        internal static string TEXT_UPDATEFORM_CAPTION_RU {
            get {
                return ResourceManager.GetString("TEXT_UPDATEFORM_CAPTION_RU", resourceCulture);
            }
        }
    }
}
